### ISSUE TITLE
couldn't recognize data in image file

### ISSUE THREAD

**Issue by atishpaul** [Cynwell/Image-Labeling-Helper#2]
Could you please solve the error while loading the image in next page?
i'm loading a PNG file.
![ss](https://user-images.githubusercontent.com/38566116/91021902-0cfe1780-e612-11ea-900f-6ba9d17ceef2.png)

**Comment by Cynwell** [comment]
It seems that the error is caused by the Tkinter module that it is unable load the .png file. Could you provide your sample codes?

I guess you loaded the .png image in this way:
`photo = PhotoImage(file='xxx.png')`

But Tkinter only works with .gif files. Therefore you might need to use other ways to read it and load it into Tkinter:
```
from PIL import Image, ImageTk
img = Image.open('xxx.png')
photo = ImageTk.PhotoImage(img)
```

In case there's no module called "PIL", you will also need to install the package by doing so: `pip install Pillow`.

**Comment by atishpaul** [comment]
I had to convert it with PIL and now its not showing any error.
do not know whats wrong with the my default PNG file,but after converting from PIL, Now its working fine.

Thanks for your Response.
